### ISSUE TITLE
how to channget the figure colors? 

### ISSUE THREAD

**Issue by rajeshkalakoti** [fcakyon/confplot#1]
```py
confplot.plot_confusion_matrix_from_data(
    y_test,
    pred,
    columns,
    figsize=(10,10),
    %colors
)
```

**Comment by rajeshkalakoti** [comment]
Hey, it's okay, i changed the colors, thank you. cmap

**Comment by rajeshkalakoti** [comment]
how to change the figure title?

**Comment by fcakyon** [comment]
@rajeshkalakoti unfortunately its hardcoded, you have to change the source: https://github.com/fcakyon/confplot/blob/93e777aae4ace838a82c2f2420d489e7bf04b960/confplot/confplot.py#L228

**Comment by rajeshkalakoti** [comment]
thank you.
